<?php


namespace AgentSIB\JsonRpcBundle\Server;

use AgentSIB\JsonRpc\JsonRpcServer AS BaseServer;
use AgentSIB\JsonRpc\Serializers\JsonRpcSerializerInterface;
use SebastianBergmann\Exporter\Exception;
use Symfony\Component\DependencyInjection\ContainerInterface;

class JsonRpcServer extends BaseServer
{
    /** @var  ContainerInterface */
    private $container;

    public function __construct (ContainerInterface $container, JsonRpcSerializerInterface $serializer)
    {
        parent::__construct($serializer);
        $this->container = $container;
    }

    public function addService ($namespace, $class)
    {
        parent::addService($namespace, $class); // TODO: Change the autogenerated stub
    }


} 